POST http://localhost:8081/events
Content-Type: application/json

{
    "name":"Test event",
    "description":"a test event",
    "location":"a test location",
    "dateTime":"2025-01-01T15:30:00.000Z"
}